//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VirtualClient.rc
//
#define IDR_MAINMENU                    101
#define IDD_LOGIN                       102
#define IDD_NEWUSER                     103
#define IDC_USERID                      1000
#define IDC_PASSWORD                    1001
#define IDC_USERNAME                    1004
#define IDC_SSNO                        1005
#define IDC_QUIZ1                       1006
#define IDC_ANSWER1                     1007
#define IDC_QUIZ2                       1008
#define IDC_ANSWER2                     1009
#define IDC_PHONE                       1010
#define IDC_MOBILEPHONE                 1011
#define IDC_EMAIL                       1012
#define IDC_BIRTHDAY                    1013
#define IDM_CM_IDPASSWORD               40001
#define IDM_CM_ADDUSER                  40002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
